---
title: Shiven Kashyap
baseurl: 
author: Shiven Kashyap
desc: I write about a lot of things here - be it FOSS, AI, psychology and even literature.
about: Hi! I'm Shiven. I'm an engineering sophomore majoring in AI and Data Science, but most importantly, I'm a FOSS author and Linux nerd. I write about topics that I find interesting when I read about them. I love listening to Jazz House, and RnB.

image: /assets/images/me.png
excerpt_separator: "<!-- more -->"
markdown: kramdown

gems:
  - jekyll-paginate

exclude:
  - .jekyll-metadata

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  
paginate: 5
paginate_path: "/:num/"

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: pretty
