title: Shiven Kashyap
author:
  name: Shiven Kashyap (@shivenkashyapp)
  email: shivenkashyap24@gmail.com

description: >
  I write about a lot of things here - be it FOSS, AI, psychology and even literature.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  
show_excerpts: true

minima:
  skin: dark
  #date_format: "%b-%d-%Y"

  social_links:
    - { platform: github,         user_url: "https://github.com/shivenkashyapp" }
    # - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    - { platform: x,              user_url: "https://x.com/shivenkashyapp" }

